In [1]:
import numpy as np

data = np.load('results/vgg19_11/0.1/best_allocation_baseline.npy')

In [4]:
data[1]

array([  11,    9,   18, ..., 1997, 1998, 1999])

In [7]:
for i in range(1, 10, 1):
    print(i)

1
2
3
4
5
6
7
8
9


In [8]:
import torch, time

t1= torch.randint(0, 99999, (1000000,))
t2= torch.randint(0, 99999, (100000000,))

def torch_intersect(t1, t2, use_unique=False):
    t1 = t1.cuda()
    t2 = t2.cuda()
    t1 = t1.unique()
    t2 = t2.unique()
        
    return torch.tensor(np.intersect1d(t1.cpu().numpy(), t2.cpu().numpy()))


def torch_intersect2(t1, t2, use_unique=False):
    t1 = t1.cuda()
    t2 = t2.cuda()
    t1 = t1.unique()
    t2 = t2.unique()
    t1=set(t1.cpu().numpy())
    t2=set(t2.cpu().numpy())    
        
    return t1.intersection(t2)

tic= time.time()
res = np.intersect1d(t1.cpu().numpy(), t2.cpu().numpy())    
print('Numpy Intersect Time:', time.time()-tic)

    
tic= time.time()
res = torch_intersect(t1, t2)
print('Tensor Intersect Time:', time.time()-tic)

Numpy Intersect Time: 6.5623509883880615


AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

In [14]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()


arr1 = np.array([['a', 'b', 'c'], ['d', 'e', 'f']])
arr2 = np.array([['f', 'e', 'd'], ['c', 'b', 'a']])
print(arr1.shape)
arr_total = np.concatenate([arr1, arr2], axis=0)
old_shape = arr_total.shape
arr1_stop = arr1.shape[0]
arr_total = np.reshape(arr_total, (-1))
targets = le.fit_transform(arr_total)
targets = torch.as_tensor(targets).view(old_shape)
targets1 = targets[:arr1_stop]
targets2 = targets[arr1_stop:]
print(targets1)
print()
print(targets2)

(2, 3)
tensor([[0, 1, 2],
        [3, 4, 5]])

tensor([[5, 4, 3],
        [2, 1, 0]])
