In [1]:
import torch
from reproduction.dataloader import CUBDataLoader
from reproduction.wrapper import PPNetWrapper
from reproduction.arguments import Arguments

device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")
print("Device:", device)

Device: cpu


In [2]:
args_filename = 'arguments/vgg19_teacher.yaml'
args = Arguments(args_filename)
model = PPNetWrapper(args, device)
model.find_nearest_patches()

Saving images: 100%|██████████| 2000/2000 [06:22<00:00,  5.22it/s]


array([[  0,   0,   0,   0,   0],
       [ 43,   0,  89,  24,  89],
       [  0,   0,   0,  82,  11],
       ...,
       [159, 168,  15, 168, 139],
       [ 19,  19, 199, 167, 199],
       [199, 195, 178,  17,  82]])

In [2]:
args_filename = 'arguments/vgg11_baseline.yaml'
args = Arguments(args_filename)
model = PPNetWrapper(args, device)
model.find_nearest_patches()

Saving images: 100%|██████████| 2000/2000 [06:46<00:00,  4.92it/s]


array([[  0,  71,  45,  99,  52],
       [ 22,  99,  99,   0,   0],
       [127, 193,   5,  51,  22],
       ...,
       [188, 196, 161, 104,  77],
       [194, 192, 150, 125, 123],
       [168,  78, 156, 164, 159]])

In [3]:
args_filename = 'arguments/vgg11_kd.yaml'
args = Arguments(args_filename)
model = PPNetWrapper(args, device)
model.find_nearest_patches()

Saving images: 100%|██████████| 2000/2000 [06:46<00:00,  4.92it/s]


array([[  0,  24,  32,   0,  82],
       [ 24,  22,   7,  24,   0],
       [  0,   0,  32,  24,  82],
       ...,
       [168, 122, 168, 195, 163],
       [199, 199, 170,  19, 167],
       [147, 195, 153, 138,  73]])

In [4]:
args_filename = 'arguments/vgg16_baseline.yaml'
args = Arguments(args_filename)
model = PPNetWrapper(args, device)
model.find_nearest_patches()

Finding patches:  12%|█▏        | 719/5994 [03:51<28:17,  3.11it/s]


KeyboardInterrupt: 

In [ ]:
args_filename = 'arguments/vgg16_kd.yaml'
args = Arguments(args_filename)
model = PPNetWrapper(args, device)
model.find_nearest_patches()